version: '3.7'

services:
  pausanias:
    build:

    environment:
      - NODE_PATH=/services/pausanias
    command: node index.js
    ports:
      - 3000:3000
    volumes:
      - ./pausanias/dist:/services/pausanias
      - ./pausanias/node_modules:/services/pausanias/node_modules
